[build-system]
requires = ["setuptools~=60.5", "wheel~=0.37.1"]
build-backend = "setuptools.build_meta"

[project]
dependencies    = [
  "dacite"
]

[tool.setuptools.packages.find]
include = ["matter_server*"]

[tool.pylint.BASIC]
class-const-naming-style = "any"
good-names = [
    "_",
    "ev",
    "ex",
    "fp",
    "i",
    "id",
    "j",
    "k",
    "Run",
    "ip",
]

[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"
# will group `import x` and `from x import` of the same module.
force_sort_within_sections = true
src_paths = [
  "custom_components",
  "matter_server/client",
  "matter_server/common",
  "matter_server/server",
  "matter_server/backports",
]
known_first_party = [
    "custom_components",
    "matter_server",
    "tests",
]
forced_separate = [
    "tests",
]
combine_as_imports = true
